
twitch_miner.mine(
    [
        Streamer("salinavdl",),
        Streamer("lies_zhara",),
        Streamer("twitchrivals",),
        "callofduty",
        "rocketleague",
        "rocketleaguemena",
        "rlesports",
        "rainbow6",
        "rainbow6br",
        "rainbow6bravo",
        "overwatchcontenders",
        "overwatchleague",
        "serpentgameplay",
        "d0cc_tv",
        "kd69z",
        "mokka020",
        "donkaaklijn",
        "morrog",
        "poloislive",
        "ohnepixel",
        "jeremyfrieser",
        "jormeneer",
        "tom_21798",
        "nlhakze",
        "dysmo",
        "xqc",
        "heffelinibundels",
        "adfsamski_",
        "buurtwachttt",
        "exerpascs",
        "nayomy_cs",
        "qiyarah",
   #sign 250k
        "surgicalgoblin",
        "entropiqteam",
        "kennys",
        "smooyacs",
        "stewie2k",
        "furioussscs",
        "lobanjicaa",
        "syrson",
        "franzj",
        "heatoncs",
        "fl0m",
        
#sign
        "gekk_",
        "beastieplays",
        "astramcs",
        "bydzeraa",
        "turboxgirl",
        "zester1337",
        "camrl_",
        "isaacyyy",
        "aidkit",
        "duckibb",
        "arumii",
        "liquidline",
        "drhupi",
#sign 10k
        "p4trickcs",
        "kr4sycs",
        "acronik_",
        "propernator",
        "0scarcsgo",
        "freshcs_",
        "missmoeppi",
        "smhqoncs",
        "cool_star05",
        "melonheadxp",
        "r3salt",
        "k1ngkebab0",
        "karistalia",
        "leacharelle",
        "chezpuf",
        "spoodah",
        "serdacsgo",
        "martinlimee",
        "s0apy",
        "al3xxandra",
        "swedcsgo",
        "l3naa",
#sign 25k
        "itsjstn",
        "sweetbootieee",
        "donacs",
        "yekindar",
        "n0rb3r7",
        "fl1tjo",
        "arsenal",
        "d0kt0r3n",
        "silkapilka_",
        "xtom223",
        "lieth",
        "headexcsgo",
        "eastahh",
        "trucklover86",
        "dima_wallhacks",
        "neok",
        "kebableee",
#sign 50k
        "blamef",
        "headtr1ckk",
        "mail09cs",
        "teawithmilkandsugar",
        "fessorcs",
        "hades1337",
        "brollancs",
        "dychacs",
        "amustycow",
        "joispoi24",
        "pago3",
        "razielero",
        "ahrora",
        "fenomm",
        "bymas",
        "bumpaah",
        "martey0",
        "mariebjonnes",
        "fribergcs",
#sign 75k
        "arrowcs",
        "pimpcsgo",
        "eggrage",
        "forky",
        "aspen_tv_",
        "freakazoid",
#sign 150k
        "themystic7hwd",
        "omeredic",
        "vector",
        "dosia_csgo",
        "strakatv",
        "izakooo",
        
        
        "faenex",
        "pewdiepie",
        "benjyfishy",
        "mongraal",
        "leakzcsgo",
        
        
        
      


    ],                                  # Array of streamers (order = priority)
    followers=False,                    # Automatic download the list of your followers
    followers_order=FollowersOrder.ASC  # Sort the followers list by follow date. ASC or DESC
)
